# Form implementation generated from reading ui file 'installer.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Installer(object):
    def setupUi(self, Installer):
        Installer.setObjectName("Installer")
        Installer.resize(600, 345)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Integral/integral-icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Installer.setWindowIcon(icon)
        Installer.setStyleSheet("background-color: #0f0f0f;")
        self.centralwidget = QtWidgets.QWidget(parent=Installer)
        self.centralwidget.setObjectName("centralwidget")
        self.pathToInstall = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pathToInstall.setGeometry(QtCore.QRect(9, 256, 490, 30))
        self.pathToInstall.setStyleSheet("QLineEdit {\n"
"background-color:  rgb(21, 21, 21);\n"
"color: white;\n"
"border: 0px solid white;\n"
"border-radius: 3px;\n"
"padding: 4px;\n"
"padding-left: 3px;\n"
"}\n"
"")
        self.pathToInstall.setObjectName("pathToInstall")
        self.SelectPath = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SelectPath.setGeometry(QtCore.QRect(510, 255, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.SelectPath.setFont(font)
        self.SelectPath.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.SelectPath.setStyleSheet("QPushButton {\n"
"background-color: rgb(21, 21, 21);\n"
"border: 0px solid white;\n"
"color: white;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color:  #212121;\n"
"}")
        self.SelectPath.setObjectName("SelectPath")
        self.install = QtWidgets.QPushButton(parent=self.centralwidget)
        self.install.setGeometry(QtCore.QRect(500, 300, 91, 31))
        self.install.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.install.setStyleSheet("QPushButton {\n"
"background-color: rgb(21, 21, 21);\n"
"border: 0px solid white;\n"
"color: white;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color:  #212121;\n"
"}")
        self.install.setObjectName("install")
        self.cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(400, 300, 91, 31))
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancel.setStyleSheet("QPushButton {\n"
"background-color: rgb(21, 21, 21);\n"
"border: 0px solid white;\n"
"color: white;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color:  #212121;\n"
"}")
        self.cancel.setObjectName("cancel")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 40, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 40, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("\n"
"color: white;\n"
"")
        self.label_3.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.label_3.setObjectName("label_3")
        self.statusLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(20, 70, 561, 181))
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 321, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white;")
        self.label_5.setObjectName("label_5")
        Installer.setCentralWidget(self.centralwidget)

        self.retranslateUi(Installer)
        QtCore.QMetaObject.connectSlotsByName(Installer)

    def retranslateUi(self, Installer):
        _translate = QtCore.QCoreApplication.translate
        Installer.setWindowTitle(_translate("Installer", "Integral installer"))
        self.SelectPath.setText(_translate("Installer", "Выбрать"))
        self.install.setText(_translate("Installer", "Установить"))
        self.cancel.setText(_translate("Installer", "Отмена"))
        self.label.setText(_translate("Installer", "Привет!"))
        self.label_2.setText(_translate("Installer", "Я установщик программы"))
        self.label_3.setText(_translate("Installer", "Integral"))
        self.label_5.setText(_translate("Installer", "Made by Revellison 2024"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Installer = QtWidgets.QMainWindow()
    ui = Ui_Installer()
    ui.setupUi(Installer)
    Installer.show()
    sys.exit(app.exec())
